### ISSUE TITLE
Cadastrar Pedido

### ISSUE THREAD

**Issue by staviasz** [staviasz/BitBarbaros#56]
POST /pedido

Lembre-se: Cada pedido deverá conter ao menos um produto vinculado.

Atenção: As propriedades produto_id e quantidade_produto devem ser informadas dentro de um array e para cada produto deverá ser criado um objeto neste array, como ilustrado no objeto de requisição abaixo. Só deverá ser cadastrado o pedido caso todos produtos vinculados ao pedido realmente existão no banco de dados.

```bash
// Corpo da requisição para cadastro de pedido (body)
{
    "cliente_id": 1,
    "observacao": "Em caso de ausência recomendo deixar com algum vizinho",
    "pedido_produtos": [
        {
            "produto_id": 1,
            "quantidade_produto": 10
        },
        {
            "produto_id": 2,
            "quantidade_produto": 20
        }
    ]
}
```

Critérios de aceite:

```bash
-   Validar os campos obrigatórios:
    -   cliente_id
    -   pedido_produtos
        -   produto_id
        -   quantidade_produto
-   Validar se existe cliente para o id enviado no corpo (body) da requisição.
-   Validar se existe produto para cada produto_id informado dentro do array enviado no corpo (body) da requisição.
-   Validar se existe a quantidade em estoque de cada produto existente dentro do array, de acordo com a quantidade informada no corpo (body) da requisição.
-   O pedido deverá ser cadastrado, apenas, se todos os produtos estiverem validados. 
-   Enviar e-mail para o cliente notificando que o pedido foi efetuado com sucesso.   
```

**Comment by staviasz** [comment]
@raulrdias encontrei alguns bugs 
- o campo observação não esta sendo validado
- falta msg para validação no array pedidos_produto para o caso dele receber algo que não seja o objeto
- msg de validar se o objeto recebido don array receber uma propriedade inesperada
- alem disso notei que o email esta sendo enviado como o valor retornado do db, porem ele esta sendo salvo em centavos, precisa ser convertido para real, obs: seria bom usar o toFixed para formatar a em moeda


![Image](https://github.com/staviasz/BitBarbaros/assets/114509017/475fe32e-be43-443b-a111-3333cec86e4f)

**Comment by raulrdias** [comment]
@staviasz tu cadastrou o produto com imagem ? deveria tá mostrando ali, vou ver isso também.
